#+TITLE: yewton.dotfiles
#+STARTUP: showall

[[https://github.com/thoughtbot/rcm][rcm]] を使って管理しています。

* macOS 初期セットアップ手順

** Control + Space をアプリに開け渡す

だいたい入力ソースの切り替えか Spotlight 関連に=⌃Space= が割り当たってると思うので、
キーボードのショートカット設定から変更する。

入力ソースの切り替えは =⌘`= に、 Spotlight は =^⌘Space= にしておく。

** ファンクションキーを使えるようにする

キーボード設定で「F1、F2などのキーを標準のファンクションキーとして使用」にチェックを入れる。

Touch Bar 搭載モデルの場合は「Touch Barに表示する項目」を「F1、F2などのキー」にする。

** キーのリピート速度を速くする

「キーのリピート」を最速に、「リピート入力認識までの時間」を最短にする。

** Homebrew を導入する

[[https://brew.sh/][公式サイト]] を見て導入を進める。

** .dotfiles を配置して必須パッケージをインストールする

#+begin_src sh
git clone https://github.com/yewton/.dotfiles.git
cd .dotfiles
brew bundle --file=Brewfiles/01_Fundamental.rb
#+end_src

** [[https://pqrs.org/osx/karabiner/][Karabiner-Elements]] を起動する

この時点から、 =caps lock= を =control= として使えるようになるなど、まともなキーボード環境が手に入る。

** rcm

#+begin_src sh
RCRC=~/.dotfiles/rcrc rcup
rcup -t macos
#+end_src

** shell の変更

#+begin_src sh
echo $(which zsh) | sudo tee -a /etc/shells
chsh -s $(which zsh)
#+end_src

ターミナルはここで終了して、以降は iTerm2 で作業する。

Application Bundle ではログインシェルの変更が反映されない場合があるので、その場合は OS 自体を再起動する。

** fzf

=brew info fzf= で Caveats を確認、指示に従い install する。

** tmux + powerline

#+BEGIN_SRC sh
  mise install
  pip install --upgrade pip
  pip install -U psutil powerline-status netifaces
#+END_SRC

** gitconfig

#+begin_src sh
git config --file ~/.gitconfig.local user.email yewton@gmail.com
git config --file ~/.gitconfig.local user.name yewton
#+end_src

** GitHub 用の credential helper

[[https://help.github.com/articles/caching-your-github-password-in-git/][公式ドキュメント]] を参考に設定する。

#+BEGIN_SRC sh
git config --file ~/.gitconfig.local credential.helper osxkeychain
#+END_SRC

** ssh config

#+begin_src sh
  mkdir -p ~/.ssh && chmod 0700 ~/.ssh && touch ~/.ssh/config && chmod 0600 ~/.ssh/config
  echo -e "Host *\n     IdentitiesOnly yes\n     ServerAliveInterval 120\n     ServerAliveCountMax 10\n     ForwardAgent yes\n     IdentityFile ~/.ssh/id_rsa\n     TCPKeepAlive yes\n     UseKeychain yes\n     AddKeysToAgent yes" >> ~/.ssh/config
#+END_SRC

** Emacs

https://github.com/yewton/.emacs.d

** other goodies

#+begin_src sh
brew bundle --file=Brewfiles/02_Common.rb
brew bundle --file=Brewfiles/03_Development.rb

gem install commonmarker
npm install -g http-server
#+end_src

** インターネットアカウント

システム環境設定から各種アカウントを設定する。

